appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: d1aiVFJ3j81Jj55G3DdVC/xYHw+psbQ66AXa9WFf80nxy5io8iGCYJYL5U1cLsDXumIJqwmXeyUxDKtXp5rXwsUxcSY0OdoGs9OUBhjPmt424oknAB3WZQzXUuUxoeSnzyCjR5xuOBXom25nW4DWHEC13nqxLdUfHuOiRWOJGL4TiaXbfwdrdaaY/e0NymPx7HG2mVVHNOOX2gRX9onzwJ3jOamneYwQEGNEnOoCEgI+OURmgAbJhz2ZoO6DvOpKiXr+6hjT7YzXnboK36Xpy8CJ3eEfKgq/TNYEm5l2q2uWZ625UTt2ca0wXfrDU729uk4DRws7vHpzHKAPJJy5Fn8Tq50X1FkeC6H5hjB3OjR8sPHUcP8B3sV2RzzXexiAAa/jCAZHFjHIWF5cbw8W8FNfKKt+xDtS9MDmT5mUUsff6SJAdPfJz3ozkTFMF7rUrnunOlT/la6bVG9I+lAn5XbfIChU+kbgxb3LtKbRvmqksQzTrbfbmG09ns3DNDmb8pUUFqr+Smu8Q3d1vod51lmezCLIEyJrkmpODTbjvaptXqiShzL+ugSwwUr2qd6+I98qvgUFKMSxHUD3LLbOiz7KeLO74m9DCQUiiVOaw+weAp1WPakjfmOylYjKDrjE9AHBI4XsefShCsFgul886/kdobgGZB4TSBBnJIb5hyU=}
